### ISSUE TITLE
Import App Configuration using ImportYamlFile (or DefinitionConfigurator)

### ISSUE THREAD

**Issue by tacman** [tacman/postgres-demo#2]
https://github.com/symfony/symfony/discussions/49827

I want to configure the columns in yaml files for the display, and leverage the Symfony yaml file loader.

```yaml
# app.yaml
  imports:
    - { resource: user.yml }
    - { resource: person.yml }


# person.yaml
tables:
  person:
    columns:
      - {name: name}
      - {name: languages, jsonb_field: info, type: array, property: languages}
      - {name: country, jsonb_field: info, type: string, property: country}


# user.yaml
tables: 
  user:    
    columns:
      - {name: email}
```

If this could pass through the DefinitionConfigurator, it could be validated 
```php
    public function configure(DefinitionConfigurator $definition): void
    {
        $definition->rootNode()
            ->children()
            ->arrayNode('tables')->defaultValue([])->end()
            ->end();
        ;
    }
```

And then inject the configuration into a service, which itself could be injected into the controller, to properly render the table columns.
